version: '3.8'
services:
  mysql-song:
    container_name: mysql-song
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: song_service
      MYSQL_USER: zingmp3
      MYSQL_PASSWORD: zingmp3
      MYSQL_TCP_PORT: 3306
    ports:
      - "3306:3306"
    restart: always
    networks:
      song-service-net:

  mysql-playlist:
    container_name: mysql-playlist
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: playlist_service
      MYSQL_USER: zingmp3
      MYSQL_PASSWORD: zingmp3
      MYSQL_TCP_PORT: 3307
    volumes:
      - ./database/mysql-playlist:/data/mysql
    ports:
      - "3307:3307"
    restart: always
    networks:
      playlist-service-net:

  song-service:
    depends_on:
      - mysql-song
    container_name: song-service
    build: ./song-service
    image: song-service
    ports:
      - "8080:8080"
      - "9090:9090"
    restart: on-failure
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-song:3306/song_service
      - GRPC_SERVER_PORT=9090
    networks:
      song-service-net:
    stdin_open: true
    tty: true

  playlist-service:
    depends_on:
      - mysql-playlist
    container_name: playlist-service
    build: ./playlist-service
    image: playlist-service
    ports:
      - "8081:8081"
    restart: on-failure
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-playlist:3307/playlist_service
    networks:
      playlist-service-net:
    stdin_open: true
    tty: true


networks:
  song-service-net:
  playlist-service-net: