version: '3.8'
services:
  mysql-song:
    container_name: mysql-song
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: song_service
      MYSQL_USER: zingmp3
      MYSQL_PASSWORD: zingmp3
      MYSQL_TCP_PORT: 3306
    ports:
      - "3306:3306"
    restart: always
    networks:
      - zingmp3-net

  song-service:
    depends_on:
      - mysql-song
    container_name: song-service
    build:
      context: .
      dockerfile: Dockerfile
    image: song-service
    restart: on-failure
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-song:3306/song_service
      - EUREKA_CLIENT_SERVICE-URL_DEFAULT-ZONE=http://discovery-service:8761/eureka
    networks:
      - zingmp3-net
    stdin_open: true
    tty: true
networks:
  zingmp3-net:
    name: zingmp3-net