version: '3.8'
services:
  mysql-song:
    container_name: mysql-song
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: song_service
      MYSQL_USER: zingmp3
      MYSQL_PASSWORD: zingmp3
      MYSQL_TCP_PORT: 3306
    ports:
      - "3306:3306"
    restart: always
    networks:
      song-service-net:

  mysql-playlist:
    container_name: mysql-playlist
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: playlist_service
      MYSQL_USER: zingmp3
      MYSQL_PASSWORD: zingmp3
      MYSQL_TCP_PORT: 3307
    volumes:
      - ./database/mysql-playlist:/data/mysql
    ports:
      - "3307:3307"
    restart: always
    networks:
      playlist-service-net:

  keycloak-mysql:
    container_name: keycloak-mysql
    image: mysql
    volumes:
      - ./mysql_keycloak_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password

networks:
  song-service-net:
  playlist-service-net: