eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      default-zone: http://discovery-service:8761/eureka


spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/zing-mp3
server:
  port: 8083
keycloak:
  domain: keycloak
  realm: zing-mp3
  client-id: user-service
  client-secret: jSLIfcd5eq2t6e0CzNid3QKUaQNP1m0x
  urls:
    auth: http://${keycloak.domain}:8080
  token-url: http://nxc-hcmus.me:8081/api/auth/token
  resource-id: user-service
springdoc:
  swagger-ui:
    oauth:
      client-id: ${keycloak.client-id}
      client-secret: ${keycloak.client-secret}