// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GrpcArtist.proto

package hcmus.zingmp3.proto;

public final class Artist {
  private Artist() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hcmus_zingmp3_proto_ArtistRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hcmus_zingmp3_proto_ArtistRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hcmus_zingmp3_proto_ArtistResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hcmus_zingmp3_proto_ArtistResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Artist.proto\022\023hcmus.zingmp3.proto\032\033goo" +
      "gle/protobuf/empty.proto\"\036\n\rArtistReques" +
      "t\022\r\n\005alias\030\001 \001(\t\"\034\n\016ArtistResponse\022\n\n\002id" +
      "\030\001 \001(\t2l\n\rArtistService\022[\n\020getArtistByAl" +
      "ias\022\".hcmus.zingmp3.proto.ArtistRequest\032" +
      "#.hcmus.zingmp3.proto.ArtistResponseB\002P\001" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_hcmus_zingmp3_proto_ArtistRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_hcmus_zingmp3_proto_ArtistRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hcmus_zingmp3_proto_ArtistRequest_descriptor,
        new java.lang.String[] { "Alias", });
    internal_static_hcmus_zingmp3_proto_ArtistResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_hcmus_zingmp3_proto_ArtistResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hcmus_zingmp3_proto_ArtistResponse_descriptor,
        new java.lang.String[] { "Id", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
