// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GrpcAudio.proto

package hcmus.zingmp3.proto;

public interface AudioFileInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hcmus.zingmp3.proto.AudioFileInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string object = 2;</code>
   * @return The object.
   */
  java.lang.String getObject();
  /**
   * <code>string object = 2;</code>
   * @return The bytes for object.
   */
  com.google.protobuf.ByteString
      getObjectBytes();

  /**
   * <code>string name = 3;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 3;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string type = 4;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>string type = 4;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>int64 size = 5;</code>
   * @return The size.
   */
  long getSize();

  /**
   * <code>int64 bitrate = 6;</code>
   * @return The bitrate.
   */
  long getBitrate();

  /**
   * <code>string url = 7;</code>
   * @return The url.
   */
  java.lang.String getUrl();
  /**
   * <code>string url = 7;</code>
   * @return The bytes for url.
   */
  com.google.protobuf.ByteString
      getUrlBytes();
}
