// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GrpcAudio.proto

package hcmus.zingmp3.proto;

public interface AudioResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hcmus.zingmp3.proto.AudioResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>.hcmus.zingmp3.proto.UploadStatus status = 2;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.hcmus.zingmp3.proto.UploadStatus status = 2;</code>
   * @return The status.
   */
  hcmus.zingmp3.proto.UploadStatus getStatus();

  /**
   * <code>string url = 3;</code>
   * @return The url.
   */
  java.lang.String getUrl();
  /**
   * <code>string url = 3;</code>
   * @return The bytes for url.
   */
  com.google.protobuf.ByteString
      getUrlBytes();
}
