// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GrpcAudio.proto

package hcmus.zingmp3.proto;

public final class Audio {
  private Audio() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hcmus_zingmp3_proto_AudioRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hcmus_zingmp3_proto_AudioRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hcmus_zingmp3_proto_AudioResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hcmus_zingmp3_proto_AudioResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hcmus_zingmp3_proto_AudioFileInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hcmus_zingmp3_proto_AudioFileInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Audio.proto\022\023hcmus.zingmp3.proto\032\033goog" +
      "le/protobuf/empty.proto\032\013Image.proto\"7\n\014" +
      "AudioRequest\022\'\n\004file\030\001 \001(\0132\031.hcmus.zingm" +
      "p3.proto.File\"[\n\rAudioResponse\022\n\n\002id\030\001 \001" +
      "(\t\0221\n\006status\030\002 \001(\0162!.hcmus.zingmp3.proto" +
      ".UploadStatus\022\013\n\003url\030\003 \001(\t\"s\n\rAudioFileI" +
      "nfo\022\n\n\002id\030\001 \001(\t\022\016\n\006object\030\002 \001(\t\022\014\n\004name\030" +
      "\003 \001(\t\022\014\n\004type\030\004 \001(\t\022\014\n\004size\030\005 \001(\003\022\017\n\007bit" +
      "rate\030\006 \001(\003\022\013\n\003url\030\007 \001(\t2\304\001\n\014AudioService" +
      "\022Q\n\007getById\022\".hcmus.zingmp3.proto.AudioF" +
      "ileInfo\032\".hcmus.zingmp3.proto.AudioFileI" +
      "nfo\022a\n\026getOrCreateIfNotExists\022!.hcmus.zi" +
      "ngmp3.proto.AudioRequest\032\".hcmus.zingmp3" +
      ".proto.AudioResponse(\001B\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
          hcmus.zingmp3.proto.Image.getDescriptor(),
        });
    internal_static_hcmus_zingmp3_proto_AudioRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_hcmus_zingmp3_proto_AudioRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hcmus_zingmp3_proto_AudioRequest_descriptor,
        new java.lang.String[] { "File", });
    internal_static_hcmus_zingmp3_proto_AudioResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_hcmus_zingmp3_proto_AudioResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hcmus_zingmp3_proto_AudioResponse_descriptor,
        new java.lang.String[] { "Id", "Status", "Url", });
    internal_static_hcmus_zingmp3_proto_AudioFileInfo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_hcmus_zingmp3_proto_AudioFileInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hcmus_zingmp3_proto_AudioFileInfo_descriptor,
        new java.lang.String[] { "Id", "Object", "Name", "Type", "Size", "Bitrate", "Url", });
    com.google.protobuf.EmptyProto.getDescriptor();
    hcmus.zingmp3.proto.Image.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
