// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GrpcAudio.proto

package hcmus.zingmp3.proto;

public interface AudioRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hcmus.zingmp3.proto.AudioRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.hcmus.zingmp3.proto.File file = 1;</code>
   * @return Whether the file field is set.
   */
  boolean hasFile();
  /**
   * <code>.hcmus.zingmp3.proto.File file = 1;</code>
   * @return The file.
   */
  hcmus.zingmp3.proto.File getFile();
  /**
   * <code>.hcmus.zingmp3.proto.File file = 1;</code>
   */
  hcmus.zingmp3.proto.FileOrBuilder getFileOrBuilder();
}
