// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GrpcAudio.proto

package hcmus.zingmp3.proto;

/**
 * Protobuf type {@code hcmus.zingmp3.proto.AudioRequest}
 */
public final class AudioRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:hcmus.zingmp3.proto.AudioRequest)
    AudioRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AudioRequest.newBuilder() to construct.
  private AudioRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AudioRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AudioRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return hcmus.zingmp3.proto.Audio.internal_static_hcmus_zingmp3_proto_AudioRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return hcmus.zingmp3.proto.Audio.internal_static_hcmus_zingmp3_proto_AudioRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            hcmus.zingmp3.proto.AudioRequest.class, hcmus.zingmp3.proto.AudioRequest.Builder.class);
  }

  public static final int FILE_FIELD_NUMBER = 1;
  private hcmus.zingmp3.proto.File file_;
  /**
   * <code>.hcmus.zingmp3.proto.File file = 1;</code>
   * @return Whether the file field is set.
   */
  @java.lang.Override
  public boolean hasFile() {
    return file_ != null;
  }
  /**
   * <code>.hcmus.zingmp3.proto.File file = 1;</code>
   * @return The file.
   */
  @java.lang.Override
  public hcmus.zingmp3.proto.File getFile() {
    return file_ == null ? hcmus.zingmp3.proto.File.getDefaultInstance() : file_;
  }
  /**
   * <code>.hcmus.zingmp3.proto.File file = 1;</code>
   */
  @java.lang.Override
  public hcmus.zingmp3.proto.FileOrBuilder getFileOrBuilder() {
    return file_ == null ? hcmus.zingmp3.proto.File.getDefaultInstance() : file_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (file_ != null) {
      output.writeMessage(1, getFile());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (file_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getFile());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof hcmus.zingmp3.proto.AudioRequest)) {
      return super.equals(obj);
    }
    hcmus.zingmp3.proto.AudioRequest other = (hcmus.zingmp3.proto.AudioRequest) obj;

    if (hasFile() != other.hasFile()) return false;
    if (hasFile()) {
      if (!getFile()
          .equals(other.getFile())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasFile()) {
      hash = (37 * hash) + FILE_FIELD_NUMBER;
      hash = (53 * hash) + getFile().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static hcmus.zingmp3.proto.AudioRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static hcmus.zingmp3.proto.AudioRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static hcmus.zingmp3.proto.AudioRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static hcmus.zingmp3.proto.AudioRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static hcmus.zingmp3.proto.AudioRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static hcmus.zingmp3.proto.AudioRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static hcmus.zingmp3.proto.AudioRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static hcmus.zingmp3.proto.AudioRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static hcmus.zingmp3.proto.AudioRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static hcmus.zingmp3.proto.AudioRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static hcmus.zingmp3.proto.AudioRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static hcmus.zingmp3.proto.AudioRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(hcmus.zingmp3.proto.AudioRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code hcmus.zingmp3.proto.AudioRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:hcmus.zingmp3.proto.AudioRequest)
      hcmus.zingmp3.proto.AudioRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return hcmus.zingmp3.proto.Audio.internal_static_hcmus_zingmp3_proto_AudioRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return hcmus.zingmp3.proto.Audio.internal_static_hcmus_zingmp3_proto_AudioRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              hcmus.zingmp3.proto.AudioRequest.class, hcmus.zingmp3.proto.AudioRequest.Builder.class);
    }

    // Construct using hcmus.zingmp3.proto.AudioRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      file_ = null;
      if (fileBuilder_ != null) {
        fileBuilder_.dispose();
        fileBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return hcmus.zingmp3.proto.Audio.internal_static_hcmus_zingmp3_proto_AudioRequest_descriptor;
    }

    @java.lang.Override
    public hcmus.zingmp3.proto.AudioRequest getDefaultInstanceForType() {
      return hcmus.zingmp3.proto.AudioRequest.getDefaultInstance();
    }

    @java.lang.Override
    public hcmus.zingmp3.proto.AudioRequest build() {
      hcmus.zingmp3.proto.AudioRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public hcmus.zingmp3.proto.AudioRequest buildPartial() {
      hcmus.zingmp3.proto.AudioRequest result = new hcmus.zingmp3.proto.AudioRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(hcmus.zingmp3.proto.AudioRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.file_ = fileBuilder_ == null
            ? file_
            : fileBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof hcmus.zingmp3.proto.AudioRequest) {
        return mergeFrom((hcmus.zingmp3.proto.AudioRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(hcmus.zingmp3.proto.AudioRequest other) {
      if (other == hcmus.zingmp3.proto.AudioRequest.getDefaultInstance()) return this;
      if (other.hasFile()) {
        mergeFile(other.getFile());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getFileFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private hcmus.zingmp3.proto.File file_;
    private com.google.protobuf.SingleFieldBuilderV3<
        hcmus.zingmp3.proto.File, hcmus.zingmp3.proto.File.Builder, hcmus.zingmp3.proto.FileOrBuilder> fileBuilder_;
    /**
     * <code>.hcmus.zingmp3.proto.File file = 1;</code>
     * @return Whether the file field is set.
     */
    public boolean hasFile() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.hcmus.zingmp3.proto.File file = 1;</code>
     * @return The file.
     */
    public hcmus.zingmp3.proto.File getFile() {
      if (fileBuilder_ == null) {
        return file_ == null ? hcmus.zingmp3.proto.File.getDefaultInstance() : file_;
      } else {
        return fileBuilder_.getMessage();
      }
    }
    /**
     * <code>.hcmus.zingmp3.proto.File file = 1;</code>
     */
    public Builder setFile(hcmus.zingmp3.proto.File value) {
      if (fileBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        file_ = value;
      } else {
        fileBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.hcmus.zingmp3.proto.File file = 1;</code>
     */
    public Builder setFile(
        hcmus.zingmp3.proto.File.Builder builderForValue) {
      if (fileBuilder_ == null) {
        file_ = builderForValue.build();
      } else {
        fileBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.hcmus.zingmp3.proto.File file = 1;</code>
     */
    public Builder mergeFile(hcmus.zingmp3.proto.File value) {
      if (fileBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          file_ != null &&
          file_ != hcmus.zingmp3.proto.File.getDefaultInstance()) {
          getFileBuilder().mergeFrom(value);
        } else {
          file_ = value;
        }
      } else {
        fileBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.hcmus.zingmp3.proto.File file = 1;</code>
     */
    public Builder clearFile() {
      bitField0_ = (bitField0_ & ~0x00000001);
      file_ = null;
      if (fileBuilder_ != null) {
        fileBuilder_.dispose();
        fileBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.hcmus.zingmp3.proto.File file = 1;</code>
     */
    public hcmus.zingmp3.proto.File.Builder getFileBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getFileFieldBuilder().getBuilder();
    }
    /**
     * <code>.hcmus.zingmp3.proto.File file = 1;</code>
     */
    public hcmus.zingmp3.proto.FileOrBuilder getFileOrBuilder() {
      if (fileBuilder_ != null) {
        return fileBuilder_.getMessageOrBuilder();
      } else {
        return file_ == null ?
            hcmus.zingmp3.proto.File.getDefaultInstance() : file_;
      }
    }
    /**
     * <code>.hcmus.zingmp3.proto.File file = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        hcmus.zingmp3.proto.File, hcmus.zingmp3.proto.File.Builder, hcmus.zingmp3.proto.FileOrBuilder> 
        getFileFieldBuilder() {
      if (fileBuilder_ == null) {
        fileBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            hcmus.zingmp3.proto.File, hcmus.zingmp3.proto.File.Builder, hcmus.zingmp3.proto.FileOrBuilder>(
                getFile(),
                getParentForChildren(),
                isClean());
        file_ = null;
      }
      return fileBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:hcmus.zingmp3.proto.AudioRequest)
  }

  // @@protoc_insertion_point(class_scope:hcmus.zingmp3.proto.AudioRequest)
  private static final hcmus.zingmp3.proto.AudioRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new hcmus.zingmp3.proto.AudioRequest();
  }

  public static hcmus.zingmp3.proto.AudioRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AudioRequest>
      PARSER = new com.google.protobuf.AbstractParser<AudioRequest>() {
    @java.lang.Override
    public AudioRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AudioRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AudioRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public hcmus.zingmp3.proto.AudioRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

