// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GrpcImage.proto

package hcmus.zingmp3.proto;

public interface FileOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hcmus.zingmp3.proto.File)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes content = 1;</code>
   * @return The content.
   */
  com.google.protobuf.ByteString getContent();
}
