// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GrpcGenre.proto

package hcmus.zingmp3.proto;

public final class Genre {
  private Genre() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hcmus_zingmp3_proto_GenreRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hcmus_zingmp3_proto_GenreRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hcmus_zingmp3_proto_GenreResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hcmus_zingmp3_proto_GenreResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Genre.proto\022\023hcmus.zingmp3.proto\032\033goog" +
      "le/protobuf/empty.proto\"\035\n\014GenreRequest\022" +
      "\r\n\005alias\030\001 \001(\t\"\033\n\rGenreResponse\022\n\n\002id\030\001 " +
      "\001(\t2h\n\014GenreService\022X\n\017getGenreByAlias\022!" +
      ".hcmus.zingmp3.proto.GenreRequest\032\".hcmu" +
      "s.zingmp3.proto.GenreResponseB\002P\001b\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_hcmus_zingmp3_proto_GenreRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_hcmus_zingmp3_proto_GenreRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hcmus_zingmp3_proto_GenreRequest_descriptor,
        new java.lang.String[] { "Alias", });
    internal_static_hcmus_zingmp3_proto_GenreResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_hcmus_zingmp3_proto_GenreResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hcmus_zingmp3_proto_GenreResponse_descriptor,
        new java.lang.String[] { "Id", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
