// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GrpcGenre.proto

package hcmus.zingmp3.proto;

public interface GenreResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hcmus.zingmp3.proto.GenreResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
