// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GrpcGenre.proto

package hcmus.zingmp3.proto;

public interface GenreRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hcmus.zingmp3.proto.GenreRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string alias = 1;</code>
   * @return The alias.
   */
  java.lang.String getAlias();
  /**
   * <code>string alias = 1;</code>
   * @return The bytes for alias.
   */
  com.google.protobuf.ByteString
      getAliasBytes();
}
