// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GrpcImage.proto

package hcmus.zingmp3.proto;

public interface ImageUploadResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hcmus.zingmp3.proto.ImageUploadResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string url = 1;</code>
   * @return The url.
   */
  java.lang.String getUrl();
  /**
   * <code>string url = 1;</code>
   * @return The bytes for url.
   */
  com.google.protobuf.ByteString
      getUrlBytes();

  /**
   * <code>.hcmus.zingmp3.proto.UploadStatus status = 2;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.hcmus.zingmp3.proto.UploadStatus status = 2;</code>
   * @return The status.
   */
  hcmus.zingmp3.proto.UploadStatus getStatus();

  /**
   * <code>string id = 3;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 3;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
