// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GrpcImage.proto

package hcmus.zingmp3.proto;

public interface ImageFileInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hcmus.zingmp3.proto.ImageFileInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string object = 2;</code>
   * @return The object.
   */
  java.lang.String getObject();
  /**
   * <code>string object = 2;</code>
   * @return The bytes for object.
   */
  com.google.protobuf.ByteString
      getObjectBytes();

  /**
   * <code>string name = 3;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 3;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string originalName = 4;</code>
   * @return The originalName.
   */
  java.lang.String getOriginalName();
  /**
   * <code>string originalName = 4;</code>
   * @return The bytes for originalName.
   */
  com.google.protobuf.ByteString
      getOriginalNameBytes();

  /**
   * <code>string contentType = 6;</code>
   * @return The contentType.
   */
  java.lang.String getContentType();
  /**
   * <code>string contentType = 6;</code>
   * @return The bytes for contentType.
   */
  com.google.protobuf.ByteString
      getContentTypeBytes();

  /**
   * <code>int64 size = 7;</code>
   * @return The size.
   */
  long getSize();

  /**
   * <code>string url = 8;</code>
   * @return The url.
   */
  java.lang.String getUrl();
  /**
   * <code>string url = 8;</code>
   * @return The bytes for url.
   */
  com.google.protobuf.ByteString
      getUrlBytes();
}
