// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GrpcImage.proto

package hcmus.zingmp3.proto;

public final class Image {
  private Image() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hcmus_zingmp3_proto_File_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hcmus_zingmp3_proto_File_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hcmus_zingmp3_proto_ImageUploadRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hcmus_zingmp3_proto_ImageUploadRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hcmus_zingmp3_proto_ImageFileInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hcmus_zingmp3_proto_ImageFileInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hcmus_zingmp3_proto_ImageUploadResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hcmus_zingmp3_proto_ImageUploadResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Image.proto\022\023hcmus.zingmp3.proto\032\033goog" +
      "le/protobuf/empty.proto\"\027\n\004File\022\017\n\007conte" +
      "nt\030\001 \001(\014\"=\n\022ImageUploadRequest\022\'\n\004file\030\001" +
      " \001(\0132\031.hcmus.zingmp3.proto.File\"\177\n\rImage" +
      "FileInfo\022\n\n\002id\030\001 \001(\t\022\016\n\006object\030\002 \001(\t\022\014\n\004" +
      "name\030\003 \001(\t\022\024\n\014originalName\030\004 \001(\t\022\023\n\013cont" +
      "entType\030\006 \001(\t\022\014\n\004size\030\007 \001(\003\022\013\n\003url\030\010 \001(\t" +
      "\"a\n\023ImageUploadResponse\022\013\n\003url\030\001 \001(\t\0221\n\006" +
      "status\030\002 \001(\0162!.hcmus.zingmp3.proto.Uploa" +
      "dStatus\022\n\n\002id\030\003 \001(\t*\'\n\014UploadStatus\022\013\n\007S" +
      "UCCESS\020\000\022\n\n\006FAILED\020\0012\331\001\n\022ImageUploadServ" +
      "ice\022S\n\007getById\022\".hcmus.zingmp3.proto.Ima" +
      "geFileInfo\032\".hcmus.zingmp3.proto.ImageFi" +
      "leInfo\"\000\022n\n\025getOrCreateIfNotExist\022\'.hcmu" +
      "s.zingmp3.proto.ImageUploadRequest\032(.hcm" +
      "us.zingmp3.proto.ImageUploadResponse\"\000(\001" +
      "B\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_hcmus_zingmp3_proto_File_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_hcmus_zingmp3_proto_File_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hcmus_zingmp3_proto_File_descriptor,
        new java.lang.String[] { "Content", });
    internal_static_hcmus_zingmp3_proto_ImageUploadRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_hcmus_zingmp3_proto_ImageUploadRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hcmus_zingmp3_proto_ImageUploadRequest_descriptor,
        new java.lang.String[] { "File", });
    internal_static_hcmus_zingmp3_proto_ImageFileInfo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_hcmus_zingmp3_proto_ImageFileInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hcmus_zingmp3_proto_ImageFileInfo_descriptor,
        new java.lang.String[] { "Id", "Object", "Name", "OriginalName", "ContentType", "Size", "Url", });
    internal_static_hcmus_zingmp3_proto_ImageUploadResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_hcmus_zingmp3_proto_ImageUploadResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hcmus_zingmp3_proto_ImageUploadResponse_descriptor,
        new java.lang.String[] { "Url", "Status", "Id", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
