// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GrpcSong.proto

package hcmus.zingmp3.proto;

public interface SongResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hcmus.zingmp3.proto.SongResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string title = 2;</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 2;</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>string alias = 3;</code>
   * @return The alias.
   */
  java.lang.String getAlias();
  /**
   * <code>string alias = 3;</code>
   * @return The bytes for alias.
   */
  com.google.protobuf.ByteString
      getAliasBytes();

  /**
   * <code>bool isOfficial = 4;</code>
   * @return The isOfficial.
   */
  boolean getIsOfficial();

  /**
   * <code>string artistNames = 5;</code>
   * @return The artistNames.
   */
  java.lang.String getArtistNames();
  /**
   * <code>string artistNames = 5;</code>
   * @return The bytes for artistNames.
   */
  com.google.protobuf.ByteString
      getArtistNamesBytes();

  /**
   * <code>repeated .hcmus.zingmp3.proto.ArtistResponse artists = 6;</code>
   */
  java.util.List<hcmus.zingmp3.proto.ArtistResponse> 
      getArtistsList();
  /**
   * <code>repeated .hcmus.zingmp3.proto.ArtistResponse artists = 6;</code>
   */
  hcmus.zingmp3.proto.ArtistResponse getArtists(int index);
  /**
   * <code>repeated .hcmus.zingmp3.proto.ArtistResponse artists = 6;</code>
   */
  int getArtistsCount();
  /**
   * <code>repeated .hcmus.zingmp3.proto.ArtistResponse artists = 6;</code>
   */
  java.util.List<? extends hcmus.zingmp3.proto.ArtistResponseOrBuilder> 
      getArtistsOrBuilderList();
  /**
   * <code>repeated .hcmus.zingmp3.proto.ArtistResponse artists = 6;</code>
   */
  hcmus.zingmp3.proto.ArtistResponseOrBuilder getArtistsOrBuilder(
      int index);

  /**
   * <code>repeated .hcmus.zingmp3.proto.GenreResponse genres = 7;</code>
   */
  java.util.List<hcmus.zingmp3.proto.GenreResponse> 
      getGenresList();
  /**
   * <code>repeated .hcmus.zingmp3.proto.GenreResponse genres = 7;</code>
   */
  hcmus.zingmp3.proto.GenreResponse getGenres(int index);
  /**
   * <code>repeated .hcmus.zingmp3.proto.GenreResponse genres = 7;</code>
   */
  int getGenresCount();
  /**
   * <code>repeated .hcmus.zingmp3.proto.GenreResponse genres = 7;</code>
   */
  java.util.List<? extends hcmus.zingmp3.proto.GenreResponseOrBuilder> 
      getGenresOrBuilderList();
  /**
   * <code>repeated .hcmus.zingmp3.proto.GenreResponse genres = 7;</code>
   */
  hcmus.zingmp3.proto.GenreResponseOrBuilder getGenresOrBuilder(
      int index);

  /**
   * <code>repeated .hcmus.zingmp3.proto.ArtistResponse composers = 8;</code>
   */
  java.util.List<hcmus.zingmp3.proto.ArtistResponse> 
      getComposersList();
  /**
   * <code>repeated .hcmus.zingmp3.proto.ArtistResponse composers = 8;</code>
   */
  hcmus.zingmp3.proto.ArtistResponse getComposers(int index);
  /**
   * <code>repeated .hcmus.zingmp3.proto.ArtistResponse composers = 8;</code>
   */
  int getComposersCount();
  /**
   * <code>repeated .hcmus.zingmp3.proto.ArtistResponse composers = 8;</code>
   */
  java.util.List<? extends hcmus.zingmp3.proto.ArtistResponseOrBuilder> 
      getComposersOrBuilderList();
  /**
   * <code>repeated .hcmus.zingmp3.proto.ArtistResponse composers = 8;</code>
   */
  hcmus.zingmp3.proto.ArtistResponseOrBuilder getComposersOrBuilder(
      int index);

  /**
   * <code>bool isWorldWide = 9;</code>
   * @return The isWorldWide.
   */
  boolean getIsWorldWide();

  /**
   * <code>int32 releaseDate = 10;</code>
   * @return The releaseDate.
   */
  int getReleaseDate();

  /**
   * <code>string distributor = 11;</code>
   * @return The distributor.
   */
  java.lang.String getDistributor();
  /**
   * <code>string distributor = 11;</code>
   * @return The bytes for distributor.
   */
  com.google.protobuf.ByteString
      getDistributorBytes();
}
