// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GrpcSong.proto

package hcmus.zingmp3.proto;

/**
 * Protobuf type {@code hcmus.zingmp3.proto.SongResponse}
 */
public final class SongResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:hcmus.zingmp3.proto.SongResponse)
    SongResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SongResponse.newBuilder() to construct.
  private SongResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SongResponse() {
    id_ = "";
    title_ = "";
    alias_ = "";
    artistNames_ = "";
    artists_ = java.util.Collections.emptyList();
    genres_ = java.util.Collections.emptyList();
    composers_ = java.util.Collections.emptyList();
    distributor_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SongResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return hcmus.zingmp3.proto.Song.internal_static_hcmus_zingmp3_proto_SongResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return hcmus.zingmp3.proto.Song.internal_static_hcmus_zingmp3_proto_SongResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            hcmus.zingmp3.proto.SongResponse.class, hcmus.zingmp3.proto.SongResponse.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object id_ = "";
  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TITLE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object title_ = "";
  /**
   * <code>string title = 2;</code>
   * @return The title.
   */
  @java.lang.Override
  public java.lang.String getTitle() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      title_ = s;
      return s;
    }
  }
  /**
   * <code>string title = 2;</code>
   * @return The bytes for title.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTitleBytes() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      title_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ALIAS_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object alias_ = "";
  /**
   * <code>string alias = 3;</code>
   * @return The alias.
   */
  @java.lang.Override
  public java.lang.String getAlias() {
    java.lang.Object ref = alias_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      alias_ = s;
      return s;
    }
  }
  /**
   * <code>string alias = 3;</code>
   * @return The bytes for alias.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAliasBytes() {
    java.lang.Object ref = alias_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      alias_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ISOFFICIAL_FIELD_NUMBER = 4;
  private boolean isOfficial_ = false;
  /**
   * <code>bool isOfficial = 4;</code>
   * @return The isOfficial.
   */
  @java.lang.Override
  public boolean getIsOfficial() {
    return isOfficial_;
  }

  public static final int ARTISTNAMES_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object artistNames_ = "";
  /**
   * <code>string artistNames = 5;</code>
   * @return The artistNames.
   */
  @java.lang.Override
  public java.lang.String getArtistNames() {
    java.lang.Object ref = artistNames_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      artistNames_ = s;
      return s;
    }
  }
  /**
   * <code>string artistNames = 5;</code>
   * @return The bytes for artistNames.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getArtistNamesBytes() {
    java.lang.Object ref = artistNames_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      artistNames_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ARTISTS_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private java.util.List<hcmus.zingmp3.proto.ArtistResponse> artists_;
  /**
   * <code>repeated .hcmus.zingmp3.proto.ArtistResponse artists = 6;</code>
   */
  @java.lang.Override
  public java.util.List<hcmus.zingmp3.proto.ArtistResponse> getArtistsList() {
    return artists_;
  }
  /**
   * <code>repeated .hcmus.zingmp3.proto.ArtistResponse artists = 6;</code>
   */
  @java.lang.Override
  public java.util.List<? extends hcmus.zingmp3.proto.ArtistResponseOrBuilder> 
      getArtistsOrBuilderList() {
    return artists_;
  }
  /**
   * <code>repeated .hcmus.zingmp3.proto.ArtistResponse artists = 6;</code>
   */
  @java.lang.Override
  public int getArtistsCount() {
    return artists_.size();
  }
  /**
   * <code>repeated .hcmus.zingmp3.proto.ArtistResponse artists = 6;</code>
   */
  @java.lang.Override
  public hcmus.zingmp3.proto.ArtistResponse getArtists(int index) {
    return artists_.get(index);
  }
  /**
   * <code>repeated .hcmus.zingmp3.proto.ArtistResponse artists = 6;</code>
   */
  @java.lang.Override
  public hcmus.zingmp3.proto.ArtistResponseOrBuilder getArtistsOrBuilder(
      int index) {
    return artists_.get(index);
  }

  public static final int GENRES_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private java.util.List<hcmus.zingmp3.proto.GenreResponse> genres_;
  /**
   * <code>repeated .hcmus.zingmp3.proto.GenreResponse genres = 7;</code>
   */
  @java.lang.Override
  public java.util.List<hcmus.zingmp3.proto.GenreResponse> getGenresList() {
    return genres_;
  }
  /**
   * <code>repeated .hcmus.zingmp3.proto.GenreResponse genres = 7;</code>
   */
  @java.lang.Override
  public java.util.List<? extends hcmus.zingmp3.proto.GenreResponseOrBuilder> 
      getGenresOrBuilderList() {
    return genres_;
  }
  /**
   * <code>repeated .hcmus.zingmp3.proto.GenreResponse genres = 7;</code>
   */
  @java.lang.Override
  public int getGenresCount() {
    return genres_.size();
  }
  /**
   * <code>repeated .hcmus.zingmp3.proto.GenreResponse genres = 7;</code>
   */
  @java.lang.Override
  public hcmus.zingmp3.proto.GenreResponse getGenres(int index) {
    return genres_.get(index);
  }
  /**
   * <code>repeated .hcmus.zingmp3.proto.GenreResponse genres = 7;</code>
   */
  @java.lang.Override
  public hcmus.zingmp3.proto.GenreResponseOrBuilder getGenresOrBuilder(
      int index) {
    return genres_.get(index);
  }

  public static final int COMPOSERS_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private java.util.List<hcmus.zingmp3.proto.ArtistResponse> composers_;
  /**
   * <code>repeated .hcmus.zingmp3.proto.ArtistResponse composers = 8;</code>
   */
  @java.lang.Override
  public java.util.List<hcmus.zingmp3.proto.ArtistResponse> getComposersList() {
    return composers_;
  }
  /**
   * <code>repeated .hcmus.zingmp3.proto.ArtistResponse composers = 8;</code>
   */
  @java.lang.Override
  public java.util.List<? extends hcmus.zingmp3.proto.ArtistResponseOrBuilder> 
      getComposersOrBuilderList() {
    return composers_;
  }
  /**
   * <code>repeated .hcmus.zingmp3.proto.ArtistResponse composers = 8;</code>
   */
  @java.lang.Override
  public int getComposersCount() {
    return composers_.size();
  }
  /**
   * <code>repeated .hcmus.zingmp3.proto.ArtistResponse composers = 8;</code>
   */
  @java.lang.Override
  public hcmus.zingmp3.proto.ArtistResponse getComposers(int index) {
    return composers_.get(index);
  }
  /**
   * <code>repeated .hcmus.zingmp3.proto.ArtistResponse composers = 8;</code>
   */
  @java.lang.Override
  public hcmus.zingmp3.proto.ArtistResponseOrBuilder getComposersOrBuilder(
      int index) {
    return composers_.get(index);
  }

  public static final int ISWORLDWIDE_FIELD_NUMBER = 9;
  private boolean isWorldWide_ = false;
  /**
   * <code>bool isWorldWide = 9;</code>
   * @return The isWorldWide.
   */
  @java.lang.Override
  public boolean getIsWorldWide() {
    return isWorldWide_;
  }

  public static final int RELEASEDATE_FIELD_NUMBER = 10;
  private int releaseDate_ = 0;
  /**
   * <code>int32 releaseDate = 10;</code>
   * @return The releaseDate.
   */
  @java.lang.Override
  public int getReleaseDate() {
    return releaseDate_;
  }

  public static final int DISTRIBUTOR_FIELD_NUMBER = 11;
  @SuppressWarnings("serial")
  private volatile java.lang.Object distributor_ = "";
  /**
   * <code>string distributor = 11;</code>
   * @return The distributor.
   */
  @java.lang.Override
  public java.lang.String getDistributor() {
    java.lang.Object ref = distributor_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      distributor_ = s;
      return s;
    }
  }
  /**
   * <code>string distributor = 11;</code>
   * @return The bytes for distributor.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDistributorBytes() {
    java.lang.Object ref = distributor_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      distributor_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, title_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(alias_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, alias_);
    }
    if (isOfficial_ != false) {
      output.writeBool(4, isOfficial_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(artistNames_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, artistNames_);
    }
    for (int i = 0; i < artists_.size(); i++) {
      output.writeMessage(6, artists_.get(i));
    }
    for (int i = 0; i < genres_.size(); i++) {
      output.writeMessage(7, genres_.get(i));
    }
    for (int i = 0; i < composers_.size(); i++) {
      output.writeMessage(8, composers_.get(i));
    }
    if (isWorldWide_ != false) {
      output.writeBool(9, isWorldWide_);
    }
    if (releaseDate_ != 0) {
      output.writeInt32(10, releaseDate_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(distributor_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, distributor_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, title_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(alias_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, alias_);
    }
    if (isOfficial_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, isOfficial_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(artistNames_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, artistNames_);
    }
    for (int i = 0; i < artists_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, artists_.get(i));
    }
    for (int i = 0; i < genres_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, genres_.get(i));
    }
    for (int i = 0; i < composers_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, composers_.get(i));
    }
    if (isWorldWide_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(9, isWorldWide_);
    }
    if (releaseDate_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(10, releaseDate_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(distributor_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, distributor_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof hcmus.zingmp3.proto.SongResponse)) {
      return super.equals(obj);
    }
    hcmus.zingmp3.proto.SongResponse other = (hcmus.zingmp3.proto.SongResponse) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (!getTitle()
        .equals(other.getTitle())) return false;
    if (!getAlias()
        .equals(other.getAlias())) return false;
    if (getIsOfficial()
        != other.getIsOfficial()) return false;
    if (!getArtistNames()
        .equals(other.getArtistNames())) return false;
    if (!getArtistsList()
        .equals(other.getArtistsList())) return false;
    if (!getGenresList()
        .equals(other.getGenresList())) return false;
    if (!getComposersList()
        .equals(other.getComposersList())) return false;
    if (getIsWorldWide()
        != other.getIsWorldWide()) return false;
    if (getReleaseDate()
        != other.getReleaseDate()) return false;
    if (!getDistributor()
        .equals(other.getDistributor())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + TITLE_FIELD_NUMBER;
    hash = (53 * hash) + getTitle().hashCode();
    hash = (37 * hash) + ALIAS_FIELD_NUMBER;
    hash = (53 * hash) + getAlias().hashCode();
    hash = (37 * hash) + ISOFFICIAL_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsOfficial());
    hash = (37 * hash) + ARTISTNAMES_FIELD_NUMBER;
    hash = (53 * hash) + getArtistNames().hashCode();
    if (getArtistsCount() > 0) {
      hash = (37 * hash) + ARTISTS_FIELD_NUMBER;
      hash = (53 * hash) + getArtistsList().hashCode();
    }
    if (getGenresCount() > 0) {
      hash = (37 * hash) + GENRES_FIELD_NUMBER;
      hash = (53 * hash) + getGenresList().hashCode();
    }
    if (getComposersCount() > 0) {
      hash = (37 * hash) + COMPOSERS_FIELD_NUMBER;
      hash = (53 * hash) + getComposersList().hashCode();
    }
    hash = (37 * hash) + ISWORLDWIDE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsWorldWide());
    hash = (37 * hash) + RELEASEDATE_FIELD_NUMBER;
    hash = (53 * hash) + getReleaseDate();
    hash = (37 * hash) + DISTRIBUTOR_FIELD_NUMBER;
    hash = (53 * hash) + getDistributor().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static hcmus.zingmp3.proto.SongResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static hcmus.zingmp3.proto.SongResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static hcmus.zingmp3.proto.SongResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static hcmus.zingmp3.proto.SongResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static hcmus.zingmp3.proto.SongResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static hcmus.zingmp3.proto.SongResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static hcmus.zingmp3.proto.SongResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static hcmus.zingmp3.proto.SongResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static hcmus.zingmp3.proto.SongResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static hcmus.zingmp3.proto.SongResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static hcmus.zingmp3.proto.SongResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static hcmus.zingmp3.proto.SongResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(hcmus.zingmp3.proto.SongResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code hcmus.zingmp3.proto.SongResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:hcmus.zingmp3.proto.SongResponse)
      hcmus.zingmp3.proto.SongResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return hcmus.zingmp3.proto.Song.internal_static_hcmus_zingmp3_proto_SongResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return hcmus.zingmp3.proto.Song.internal_static_hcmus_zingmp3_proto_SongResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              hcmus.zingmp3.proto.SongResponse.class, hcmus.zingmp3.proto.SongResponse.Builder.class);
    }

    // Construct using hcmus.zingmp3.proto.SongResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = "";
      title_ = "";
      alias_ = "";
      isOfficial_ = false;
      artistNames_ = "";
      if (artistsBuilder_ == null) {
        artists_ = java.util.Collections.emptyList();
      } else {
        artists_ = null;
        artistsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000020);
      if (genresBuilder_ == null) {
        genres_ = java.util.Collections.emptyList();
      } else {
        genres_ = null;
        genresBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000040);
      if (composersBuilder_ == null) {
        composers_ = java.util.Collections.emptyList();
      } else {
        composers_ = null;
        composersBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000080);
      isWorldWide_ = false;
      releaseDate_ = 0;
      distributor_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return hcmus.zingmp3.proto.Song.internal_static_hcmus_zingmp3_proto_SongResponse_descriptor;
    }

    @java.lang.Override
    public hcmus.zingmp3.proto.SongResponse getDefaultInstanceForType() {
      return hcmus.zingmp3.proto.SongResponse.getDefaultInstance();
    }

    @java.lang.Override
    public hcmus.zingmp3.proto.SongResponse build() {
      hcmus.zingmp3.proto.SongResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public hcmus.zingmp3.proto.SongResponse buildPartial() {
      hcmus.zingmp3.proto.SongResponse result = new hcmus.zingmp3.proto.SongResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(hcmus.zingmp3.proto.SongResponse result) {
      if (artistsBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0)) {
          artists_ = java.util.Collections.unmodifiableList(artists_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.artists_ = artists_;
      } else {
        result.artists_ = artistsBuilder_.build();
      }
      if (genresBuilder_ == null) {
        if (((bitField0_ & 0x00000040) != 0)) {
          genres_ = java.util.Collections.unmodifiableList(genres_);
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.genres_ = genres_;
      } else {
        result.genres_ = genresBuilder_.build();
      }
      if (composersBuilder_ == null) {
        if (((bitField0_ & 0x00000080) != 0)) {
          composers_ = java.util.Collections.unmodifiableList(composers_);
          bitField0_ = (bitField0_ & ~0x00000080);
        }
        result.composers_ = composers_;
      } else {
        result.composers_ = composersBuilder_.build();
      }
    }

    private void buildPartial0(hcmus.zingmp3.proto.SongResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.title_ = title_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.alias_ = alias_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.isOfficial_ = isOfficial_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.artistNames_ = artistNames_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.isWorldWide_ = isWorldWide_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.releaseDate_ = releaseDate_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.distributor_ = distributor_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof hcmus.zingmp3.proto.SongResponse) {
        return mergeFrom((hcmus.zingmp3.proto.SongResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(hcmus.zingmp3.proto.SongResponse other) {
      if (other == hcmus.zingmp3.proto.SongResponse.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getTitle().isEmpty()) {
        title_ = other.title_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getAlias().isEmpty()) {
        alias_ = other.alias_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.getIsOfficial() != false) {
        setIsOfficial(other.getIsOfficial());
      }
      if (!other.getArtistNames().isEmpty()) {
        artistNames_ = other.artistNames_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (artistsBuilder_ == null) {
        if (!other.artists_.isEmpty()) {
          if (artists_.isEmpty()) {
            artists_ = other.artists_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureArtistsIsMutable();
            artists_.addAll(other.artists_);
          }
          onChanged();
        }
      } else {
        if (!other.artists_.isEmpty()) {
          if (artistsBuilder_.isEmpty()) {
            artistsBuilder_.dispose();
            artistsBuilder_ = null;
            artists_ = other.artists_;
            bitField0_ = (bitField0_ & ~0x00000020);
            artistsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getArtistsFieldBuilder() : null;
          } else {
            artistsBuilder_.addAllMessages(other.artists_);
          }
        }
      }
      if (genresBuilder_ == null) {
        if (!other.genres_.isEmpty()) {
          if (genres_.isEmpty()) {
            genres_ = other.genres_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensureGenresIsMutable();
            genres_.addAll(other.genres_);
          }
          onChanged();
        }
      } else {
        if (!other.genres_.isEmpty()) {
          if (genresBuilder_.isEmpty()) {
            genresBuilder_.dispose();
            genresBuilder_ = null;
            genres_ = other.genres_;
            bitField0_ = (bitField0_ & ~0x00000040);
            genresBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getGenresFieldBuilder() : null;
          } else {
            genresBuilder_.addAllMessages(other.genres_);
          }
        }
      }
      if (composersBuilder_ == null) {
        if (!other.composers_.isEmpty()) {
          if (composers_.isEmpty()) {
            composers_ = other.composers_;
            bitField0_ = (bitField0_ & ~0x00000080);
          } else {
            ensureComposersIsMutable();
            composers_.addAll(other.composers_);
          }
          onChanged();
        }
      } else {
        if (!other.composers_.isEmpty()) {
          if (composersBuilder_.isEmpty()) {
            composersBuilder_.dispose();
            composersBuilder_ = null;
            composers_ = other.composers_;
            bitField0_ = (bitField0_ & ~0x00000080);
            composersBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getComposersFieldBuilder() : null;
          } else {
            composersBuilder_.addAllMessages(other.composers_);
          }
        }
      }
      if (other.getIsWorldWide() != false) {
        setIsWorldWide(other.getIsWorldWide());
      }
      if (other.getReleaseDate() != 0) {
        setReleaseDate(other.getReleaseDate());
      }
      if (!other.getDistributor().isEmpty()) {
        distributor_ = other.distributor_;
        bitField0_ |= 0x00000400;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              id_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              title_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              alias_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              isOfficial_ = input.readBool();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              artistNames_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              hcmus.zingmp3.proto.ArtistResponse m =
                  input.readMessage(
                      hcmus.zingmp3.proto.ArtistResponse.parser(),
                      extensionRegistry);
              if (artistsBuilder_ == null) {
                ensureArtistsIsMutable();
                artists_.add(m);
              } else {
                artistsBuilder_.addMessage(m);
              }
              break;
            } // case 50
            case 58: {
              hcmus.zingmp3.proto.GenreResponse m =
                  input.readMessage(
                      hcmus.zingmp3.proto.GenreResponse.parser(),
                      extensionRegistry);
              if (genresBuilder_ == null) {
                ensureGenresIsMutable();
                genres_.add(m);
              } else {
                genresBuilder_.addMessage(m);
              }
              break;
            } // case 58
            case 66: {
              hcmus.zingmp3.proto.ArtistResponse m =
                  input.readMessage(
                      hcmus.zingmp3.proto.ArtistResponse.parser(),
                      extensionRegistry);
              if (composersBuilder_ == null) {
                ensureComposersIsMutable();
                composers_.add(m);
              } else {
                composersBuilder_.addMessage(m);
              }
              break;
            } // case 66
            case 72: {
              isWorldWide_ = input.readBool();
              bitField0_ |= 0x00000100;
              break;
            } // case 72
            case 80: {
              releaseDate_ = input.readInt32();
              bitField0_ |= 0x00000200;
              break;
            } // case 80
            case 90: {
              distributor_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000400;
              break;
            } // case 90
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      id_ = getDefaultInstance().getId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object title_ = "";
    /**
     * <code>string title = 2;</code>
     * @return The title.
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string title = 2;</code>
     * @return The bytes for title.
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string title = 2;</code>
     * @param value The title to set.
     * @return This builder for chaining.
     */
    public Builder setTitle(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      title_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string title = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTitle() {
      title_ = getDefaultInstance().getTitle();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string title = 2;</code>
     * @param value The bytes for title to set.
     * @return This builder for chaining.
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      title_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object alias_ = "";
    /**
     * <code>string alias = 3;</code>
     * @return The alias.
     */
    public java.lang.String getAlias() {
      java.lang.Object ref = alias_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        alias_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string alias = 3;</code>
     * @return The bytes for alias.
     */
    public com.google.protobuf.ByteString
        getAliasBytes() {
      java.lang.Object ref = alias_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        alias_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string alias = 3;</code>
     * @param value The alias to set.
     * @return This builder for chaining.
     */
    public Builder setAlias(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      alias_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string alias = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearAlias() {
      alias_ = getDefaultInstance().getAlias();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string alias = 3;</code>
     * @param value The bytes for alias to set.
     * @return This builder for chaining.
     */
    public Builder setAliasBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      alias_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private boolean isOfficial_ ;
    /**
     * <code>bool isOfficial = 4;</code>
     * @return The isOfficial.
     */
    @java.lang.Override
    public boolean getIsOfficial() {
      return isOfficial_;
    }
    /**
     * <code>bool isOfficial = 4;</code>
     * @param value The isOfficial to set.
     * @return This builder for chaining.
     */
    public Builder setIsOfficial(boolean value) {

      isOfficial_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>bool isOfficial = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsOfficial() {
      bitField0_ = (bitField0_ & ~0x00000008);
      isOfficial_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object artistNames_ = "";
    /**
     * <code>string artistNames = 5;</code>
     * @return The artistNames.
     */
    public java.lang.String getArtistNames() {
      java.lang.Object ref = artistNames_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        artistNames_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string artistNames = 5;</code>
     * @return The bytes for artistNames.
     */
    public com.google.protobuf.ByteString
        getArtistNamesBytes() {
      java.lang.Object ref = artistNames_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        artistNames_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string artistNames = 5;</code>
     * @param value The artistNames to set.
     * @return This builder for chaining.
     */
    public Builder setArtistNames(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      artistNames_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string artistNames = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearArtistNames() {
      artistNames_ = getDefaultInstance().getArtistNames();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string artistNames = 5;</code>
     * @param value The bytes for artistNames to set.
     * @return This builder for chaining.
     */
    public Builder setArtistNamesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      artistNames_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.util.List<hcmus.zingmp3.proto.ArtistResponse> artists_ =
      java.util.Collections.emptyList();
    private void ensureArtistsIsMutable() {
      if (!((bitField0_ & 0x00000020) != 0)) {
        artists_ = new java.util.ArrayList<hcmus.zingmp3.proto.ArtistResponse>(artists_);
        bitField0_ |= 0x00000020;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        hcmus.zingmp3.proto.ArtistResponse, hcmus.zingmp3.proto.ArtistResponse.Builder, hcmus.zingmp3.proto.ArtistResponseOrBuilder> artistsBuilder_;

    /**
     * <code>repeated .hcmus.zingmp3.proto.ArtistResponse artists = 6;</code>
     */
    public java.util.List<hcmus.zingmp3.proto.ArtistResponse> getArtistsList() {
      if (artistsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(artists_);
      } else {
        return artistsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .hcmus.zingmp3.proto.ArtistResponse artists = 6;</code>
     */
    public int getArtistsCount() {
      if (artistsBuilder_ == null) {
        return artists_.size();
      } else {
        return artistsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .hcmus.zingmp3.proto.ArtistResponse artists = 6;</code>
     */
    public hcmus.zingmp3.proto.ArtistResponse getArtists(int index) {
      if (artistsBuilder_ == null) {
        return artists_.get(index);
      } else {
        return artistsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .hcmus.zingmp3.proto.ArtistResponse artists = 6;</code>
     */
    public Builder setArtists(
        int index, hcmus.zingmp3.proto.ArtistResponse value) {
      if (artistsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureArtistsIsMutable();
        artists_.set(index, value);
        onChanged();
      } else {
        artistsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .hcmus.zingmp3.proto.ArtistResponse artists = 6;</code>
     */
    public Builder setArtists(
        int index, hcmus.zingmp3.proto.ArtistResponse.Builder builderForValue) {
      if (artistsBuilder_ == null) {
        ensureArtistsIsMutable();
        artists_.set(index, builderForValue.build());
        onChanged();
      } else {
        artistsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .hcmus.zingmp3.proto.ArtistResponse artists = 6;</code>
     */
    public Builder addArtists(hcmus.zingmp3.proto.ArtistResponse value) {
      if (artistsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureArtistsIsMutable();
        artists_.add(value);
        onChanged();
      } else {
        artistsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .hcmus.zingmp3.proto.ArtistResponse artists = 6;</code>
     */
    public Builder addArtists(
        int index, hcmus.zingmp3.proto.ArtistResponse value) {
      if (artistsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureArtistsIsMutable();
        artists_.add(index, value);
        onChanged();
      } else {
        artistsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .hcmus.zingmp3.proto.ArtistResponse artists = 6;</code>
     */
    public Builder addArtists(
        hcmus.zingmp3.proto.ArtistResponse.Builder builderForValue) {
      if (artistsBuilder_ == null) {
        ensureArtistsIsMutable();
        artists_.add(builderForValue.build());
        onChanged();
      } else {
        artistsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .hcmus.zingmp3.proto.ArtistResponse artists = 6;</code>
     */
    public Builder addArtists(
        int index, hcmus.zingmp3.proto.ArtistResponse.Builder builderForValue) {
      if (artistsBuilder_ == null) {
        ensureArtistsIsMutable();
        artists_.add(index, builderForValue.build());
        onChanged();
      } else {
        artistsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .hcmus.zingmp3.proto.ArtistResponse artists = 6;</code>
     */
    public Builder addAllArtists(
        java.lang.Iterable<? extends hcmus.zingmp3.proto.ArtistResponse> values) {
      if (artistsBuilder_ == null) {
        ensureArtistsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, artists_);
        onChanged();
      } else {
        artistsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .hcmus.zingmp3.proto.ArtistResponse artists = 6;</code>
     */
    public Builder clearArtists() {
      if (artistsBuilder_ == null) {
        artists_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
      } else {
        artistsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .hcmus.zingmp3.proto.ArtistResponse artists = 6;</code>
     */
    public Builder removeArtists(int index) {
      if (artistsBuilder_ == null) {
        ensureArtistsIsMutable();
        artists_.remove(index);
        onChanged();
      } else {
        artistsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .hcmus.zingmp3.proto.ArtistResponse artists = 6;</code>
     */
    public hcmus.zingmp3.proto.ArtistResponse.Builder getArtistsBuilder(
        int index) {
      return getArtistsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .hcmus.zingmp3.proto.ArtistResponse artists = 6;</code>
     */
    public hcmus.zingmp3.proto.ArtistResponseOrBuilder getArtistsOrBuilder(
        int index) {
      if (artistsBuilder_ == null) {
        return artists_.get(index);  } else {
        return artistsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .hcmus.zingmp3.proto.ArtistResponse artists = 6;</code>
     */
    public java.util.List<? extends hcmus.zingmp3.proto.ArtistResponseOrBuilder> 
         getArtistsOrBuilderList() {
      if (artistsBuilder_ != null) {
        return artistsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(artists_);
      }
    }
    /**
     * <code>repeated .hcmus.zingmp3.proto.ArtistResponse artists = 6;</code>
     */
    public hcmus.zingmp3.proto.ArtistResponse.Builder addArtistsBuilder() {
      return getArtistsFieldBuilder().addBuilder(
          hcmus.zingmp3.proto.ArtistResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .hcmus.zingmp3.proto.ArtistResponse artists = 6;</code>
     */
    public hcmus.zingmp3.proto.ArtistResponse.Builder addArtistsBuilder(
        int index) {
      return getArtistsFieldBuilder().addBuilder(
          index, hcmus.zingmp3.proto.ArtistResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .hcmus.zingmp3.proto.ArtistResponse artists = 6;</code>
     */
    public java.util.List<hcmus.zingmp3.proto.ArtistResponse.Builder> 
         getArtistsBuilderList() {
      return getArtistsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        hcmus.zingmp3.proto.ArtistResponse, hcmus.zingmp3.proto.ArtistResponse.Builder, hcmus.zingmp3.proto.ArtistResponseOrBuilder> 
        getArtistsFieldBuilder() {
      if (artistsBuilder_ == null) {
        artistsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            hcmus.zingmp3.proto.ArtistResponse, hcmus.zingmp3.proto.ArtistResponse.Builder, hcmus.zingmp3.proto.ArtistResponseOrBuilder>(
                artists_,
                ((bitField0_ & 0x00000020) != 0),
                getParentForChildren(),
                isClean());
        artists_ = null;
      }
      return artistsBuilder_;
    }

    private java.util.List<hcmus.zingmp3.proto.GenreResponse> genres_ =
      java.util.Collections.emptyList();
    private void ensureGenresIsMutable() {
      if (!((bitField0_ & 0x00000040) != 0)) {
        genres_ = new java.util.ArrayList<hcmus.zingmp3.proto.GenreResponse>(genres_);
        bitField0_ |= 0x00000040;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        hcmus.zingmp3.proto.GenreResponse, hcmus.zingmp3.proto.GenreResponse.Builder, hcmus.zingmp3.proto.GenreResponseOrBuilder> genresBuilder_;

    /**
     * <code>repeated .hcmus.zingmp3.proto.GenreResponse genres = 7;</code>
     */
    public java.util.List<hcmus.zingmp3.proto.GenreResponse> getGenresList() {
      if (genresBuilder_ == null) {
        return java.util.Collections.unmodifiableList(genres_);
      } else {
        return genresBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .hcmus.zingmp3.proto.GenreResponse genres = 7;</code>
     */
    public int getGenresCount() {
      if (genresBuilder_ == null) {
        return genres_.size();
      } else {
        return genresBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .hcmus.zingmp3.proto.GenreResponse genres = 7;</code>
     */
    public hcmus.zingmp3.proto.GenreResponse getGenres(int index) {
      if (genresBuilder_ == null) {
        return genres_.get(index);
      } else {
        return genresBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .hcmus.zingmp3.proto.GenreResponse genres = 7;</code>
     */
    public Builder setGenres(
        int index, hcmus.zingmp3.proto.GenreResponse value) {
      if (genresBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGenresIsMutable();
        genres_.set(index, value);
        onChanged();
      } else {
        genresBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .hcmus.zingmp3.proto.GenreResponse genres = 7;</code>
     */
    public Builder setGenres(
        int index, hcmus.zingmp3.proto.GenreResponse.Builder builderForValue) {
      if (genresBuilder_ == null) {
        ensureGenresIsMutable();
        genres_.set(index, builderForValue.build());
        onChanged();
      } else {
        genresBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .hcmus.zingmp3.proto.GenreResponse genres = 7;</code>
     */
    public Builder addGenres(hcmus.zingmp3.proto.GenreResponse value) {
      if (genresBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGenresIsMutable();
        genres_.add(value);
        onChanged();
      } else {
        genresBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .hcmus.zingmp3.proto.GenreResponse genres = 7;</code>
     */
    public Builder addGenres(
        int index, hcmus.zingmp3.proto.GenreResponse value) {
      if (genresBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGenresIsMutable();
        genres_.add(index, value);
        onChanged();
      } else {
        genresBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .hcmus.zingmp3.proto.GenreResponse genres = 7;</code>
     */
    public Builder addGenres(
        hcmus.zingmp3.proto.GenreResponse.Builder builderForValue) {
      if (genresBuilder_ == null) {
        ensureGenresIsMutable();
        genres_.add(builderForValue.build());
        onChanged();
      } else {
        genresBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .hcmus.zingmp3.proto.GenreResponse genres = 7;</code>
     */
    public Builder addGenres(
        int index, hcmus.zingmp3.proto.GenreResponse.Builder builderForValue) {
      if (genresBuilder_ == null) {
        ensureGenresIsMutable();
        genres_.add(index, builderForValue.build());
        onChanged();
      } else {
        genresBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .hcmus.zingmp3.proto.GenreResponse genres = 7;</code>
     */
    public Builder addAllGenres(
        java.lang.Iterable<? extends hcmus.zingmp3.proto.GenreResponse> values) {
      if (genresBuilder_ == null) {
        ensureGenresIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, genres_);
        onChanged();
      } else {
        genresBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .hcmus.zingmp3.proto.GenreResponse genres = 7;</code>
     */
    public Builder clearGenres() {
      if (genresBuilder_ == null) {
        genres_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
      } else {
        genresBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .hcmus.zingmp3.proto.GenreResponse genres = 7;</code>
     */
    public Builder removeGenres(int index) {
      if (genresBuilder_ == null) {
        ensureGenresIsMutable();
        genres_.remove(index);
        onChanged();
      } else {
        genresBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .hcmus.zingmp3.proto.GenreResponse genres = 7;</code>
     */
    public hcmus.zingmp3.proto.GenreResponse.Builder getGenresBuilder(
        int index) {
      return getGenresFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .hcmus.zingmp3.proto.GenreResponse genres = 7;</code>
     */
    public hcmus.zingmp3.proto.GenreResponseOrBuilder getGenresOrBuilder(
        int index) {
      if (genresBuilder_ == null) {
        return genres_.get(index);  } else {
        return genresBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .hcmus.zingmp3.proto.GenreResponse genres = 7;</code>
     */
    public java.util.List<? extends hcmus.zingmp3.proto.GenreResponseOrBuilder> 
         getGenresOrBuilderList() {
      if (genresBuilder_ != null) {
        return genresBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(genres_);
      }
    }
    /**
     * <code>repeated .hcmus.zingmp3.proto.GenreResponse genres = 7;</code>
     */
    public hcmus.zingmp3.proto.GenreResponse.Builder addGenresBuilder() {
      return getGenresFieldBuilder().addBuilder(
          hcmus.zingmp3.proto.GenreResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .hcmus.zingmp3.proto.GenreResponse genres = 7;</code>
     */
    public hcmus.zingmp3.proto.GenreResponse.Builder addGenresBuilder(
        int index) {
      return getGenresFieldBuilder().addBuilder(
          index, hcmus.zingmp3.proto.GenreResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .hcmus.zingmp3.proto.GenreResponse genres = 7;</code>
     */
    public java.util.List<hcmus.zingmp3.proto.GenreResponse.Builder> 
         getGenresBuilderList() {
      return getGenresFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        hcmus.zingmp3.proto.GenreResponse, hcmus.zingmp3.proto.GenreResponse.Builder, hcmus.zingmp3.proto.GenreResponseOrBuilder> 
        getGenresFieldBuilder() {
      if (genresBuilder_ == null) {
        genresBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            hcmus.zingmp3.proto.GenreResponse, hcmus.zingmp3.proto.GenreResponse.Builder, hcmus.zingmp3.proto.GenreResponseOrBuilder>(
                genres_,
                ((bitField0_ & 0x00000040) != 0),
                getParentForChildren(),
                isClean());
        genres_ = null;
      }
      return genresBuilder_;
    }

    private java.util.List<hcmus.zingmp3.proto.ArtistResponse> composers_ =
      java.util.Collections.emptyList();
    private void ensureComposersIsMutable() {
      if (!((bitField0_ & 0x00000080) != 0)) {
        composers_ = new java.util.ArrayList<hcmus.zingmp3.proto.ArtistResponse>(composers_);
        bitField0_ |= 0x00000080;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        hcmus.zingmp3.proto.ArtistResponse, hcmus.zingmp3.proto.ArtistResponse.Builder, hcmus.zingmp3.proto.ArtistResponseOrBuilder> composersBuilder_;

    /**
     * <code>repeated .hcmus.zingmp3.proto.ArtistResponse composers = 8;</code>
     */
    public java.util.List<hcmus.zingmp3.proto.ArtistResponse> getComposersList() {
      if (composersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(composers_);
      } else {
        return composersBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .hcmus.zingmp3.proto.ArtistResponse composers = 8;</code>
     */
    public int getComposersCount() {
      if (composersBuilder_ == null) {
        return composers_.size();
      } else {
        return composersBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .hcmus.zingmp3.proto.ArtistResponse composers = 8;</code>
     */
    public hcmus.zingmp3.proto.ArtistResponse getComposers(int index) {
      if (composersBuilder_ == null) {
        return composers_.get(index);
      } else {
        return composersBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .hcmus.zingmp3.proto.ArtistResponse composers = 8;</code>
     */
    public Builder setComposers(
        int index, hcmus.zingmp3.proto.ArtistResponse value) {
      if (composersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureComposersIsMutable();
        composers_.set(index, value);
        onChanged();
      } else {
        composersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .hcmus.zingmp3.proto.ArtistResponse composers = 8;</code>
     */
    public Builder setComposers(
        int index, hcmus.zingmp3.proto.ArtistResponse.Builder builderForValue) {
      if (composersBuilder_ == null) {
        ensureComposersIsMutable();
        composers_.set(index, builderForValue.build());
        onChanged();
      } else {
        composersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .hcmus.zingmp3.proto.ArtistResponse composers = 8;</code>
     */
    public Builder addComposers(hcmus.zingmp3.proto.ArtistResponse value) {
      if (composersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureComposersIsMutable();
        composers_.add(value);
        onChanged();
      } else {
        composersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .hcmus.zingmp3.proto.ArtistResponse composers = 8;</code>
     */
    public Builder addComposers(
        int index, hcmus.zingmp3.proto.ArtistResponse value) {
      if (composersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureComposersIsMutable();
        composers_.add(index, value);
        onChanged();
      } else {
        composersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .hcmus.zingmp3.proto.ArtistResponse composers = 8;</code>
     */
    public Builder addComposers(
        hcmus.zingmp3.proto.ArtistResponse.Builder builderForValue) {
      if (composersBuilder_ == null) {
        ensureComposersIsMutable();
        composers_.add(builderForValue.build());
        onChanged();
      } else {
        composersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .hcmus.zingmp3.proto.ArtistResponse composers = 8;</code>
     */
    public Builder addComposers(
        int index, hcmus.zingmp3.proto.ArtistResponse.Builder builderForValue) {
      if (composersBuilder_ == null) {
        ensureComposersIsMutable();
        composers_.add(index, builderForValue.build());
        onChanged();
      } else {
        composersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .hcmus.zingmp3.proto.ArtistResponse composers = 8;</code>
     */
    public Builder addAllComposers(
        java.lang.Iterable<? extends hcmus.zingmp3.proto.ArtistResponse> values) {
      if (composersBuilder_ == null) {
        ensureComposersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, composers_);
        onChanged();
      } else {
        composersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .hcmus.zingmp3.proto.ArtistResponse composers = 8;</code>
     */
    public Builder clearComposers() {
      if (composersBuilder_ == null) {
        composers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
      } else {
        composersBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .hcmus.zingmp3.proto.ArtistResponse composers = 8;</code>
     */
    public Builder removeComposers(int index) {
      if (composersBuilder_ == null) {
        ensureComposersIsMutable();
        composers_.remove(index);
        onChanged();
      } else {
        composersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .hcmus.zingmp3.proto.ArtistResponse composers = 8;</code>
     */
    public hcmus.zingmp3.proto.ArtistResponse.Builder getComposersBuilder(
        int index) {
      return getComposersFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .hcmus.zingmp3.proto.ArtistResponse composers = 8;</code>
     */
    public hcmus.zingmp3.proto.ArtistResponseOrBuilder getComposersOrBuilder(
        int index) {
      if (composersBuilder_ == null) {
        return composers_.get(index);  } else {
        return composersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .hcmus.zingmp3.proto.ArtistResponse composers = 8;</code>
     */
    public java.util.List<? extends hcmus.zingmp3.proto.ArtistResponseOrBuilder> 
         getComposersOrBuilderList() {
      if (composersBuilder_ != null) {
        return composersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(composers_);
      }
    }
    /**
     * <code>repeated .hcmus.zingmp3.proto.ArtistResponse composers = 8;</code>
     */
    public hcmus.zingmp3.proto.ArtistResponse.Builder addComposersBuilder() {
      return getComposersFieldBuilder().addBuilder(
          hcmus.zingmp3.proto.ArtistResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .hcmus.zingmp3.proto.ArtistResponse composers = 8;</code>
     */
    public hcmus.zingmp3.proto.ArtistResponse.Builder addComposersBuilder(
        int index) {
      return getComposersFieldBuilder().addBuilder(
          index, hcmus.zingmp3.proto.ArtistResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .hcmus.zingmp3.proto.ArtistResponse composers = 8;</code>
     */
    public java.util.List<hcmus.zingmp3.proto.ArtistResponse.Builder> 
         getComposersBuilderList() {
      return getComposersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        hcmus.zingmp3.proto.ArtistResponse, hcmus.zingmp3.proto.ArtistResponse.Builder, hcmus.zingmp3.proto.ArtistResponseOrBuilder> 
        getComposersFieldBuilder() {
      if (composersBuilder_ == null) {
        composersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            hcmus.zingmp3.proto.ArtistResponse, hcmus.zingmp3.proto.ArtistResponse.Builder, hcmus.zingmp3.proto.ArtistResponseOrBuilder>(
                composers_,
                ((bitField0_ & 0x00000080) != 0),
                getParentForChildren(),
                isClean());
        composers_ = null;
      }
      return composersBuilder_;
    }

    private boolean isWorldWide_ ;
    /**
     * <code>bool isWorldWide = 9;</code>
     * @return The isWorldWide.
     */
    @java.lang.Override
    public boolean getIsWorldWide() {
      return isWorldWide_;
    }
    /**
     * <code>bool isWorldWide = 9;</code>
     * @param value The isWorldWide to set.
     * @return This builder for chaining.
     */
    public Builder setIsWorldWide(boolean value) {

      isWorldWide_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>bool isWorldWide = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsWorldWide() {
      bitField0_ = (bitField0_ & ~0x00000100);
      isWorldWide_ = false;
      onChanged();
      return this;
    }

    private int releaseDate_ ;
    /**
     * <code>int32 releaseDate = 10;</code>
     * @return The releaseDate.
     */
    @java.lang.Override
    public int getReleaseDate() {
      return releaseDate_;
    }
    /**
     * <code>int32 releaseDate = 10;</code>
     * @param value The releaseDate to set.
     * @return This builder for chaining.
     */
    public Builder setReleaseDate(int value) {

      releaseDate_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>int32 releaseDate = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearReleaseDate() {
      bitField0_ = (bitField0_ & ~0x00000200);
      releaseDate_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object distributor_ = "";
    /**
     * <code>string distributor = 11;</code>
     * @return The distributor.
     */
    public java.lang.String getDistributor() {
      java.lang.Object ref = distributor_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        distributor_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string distributor = 11;</code>
     * @return The bytes for distributor.
     */
    public com.google.protobuf.ByteString
        getDistributorBytes() {
      java.lang.Object ref = distributor_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        distributor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string distributor = 11;</code>
     * @param value The distributor to set.
     * @return This builder for chaining.
     */
    public Builder setDistributor(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      distributor_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>string distributor = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearDistributor() {
      distributor_ = getDefaultInstance().getDistributor();
      bitField0_ = (bitField0_ & ~0x00000400);
      onChanged();
      return this;
    }
    /**
     * <code>string distributor = 11;</code>
     * @param value The bytes for distributor to set.
     * @return This builder for chaining.
     */
    public Builder setDistributorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      distributor_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:hcmus.zingmp3.proto.SongResponse)
  }

  // @@protoc_insertion_point(class_scope:hcmus.zingmp3.proto.SongResponse)
  private static final hcmus.zingmp3.proto.SongResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new hcmus.zingmp3.proto.SongResponse();
  }

  public static hcmus.zingmp3.proto.SongResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SongResponse>
      PARSER = new com.google.protobuf.AbstractParser<SongResponse>() {
    @java.lang.Override
    public SongResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SongResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SongResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public hcmus.zingmp3.proto.SongResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

