@host = nxc-hcmus.me

### get access token
POST http://{{host}}:8081/api/auth/token
Content-Type: application/x-www-form-urlencoded

client_id = zing-mp3-api &
client_secret = nGZ3VfUaC8CrnmSEs8wK1J15M4PY1lUD &
grant_type = password &
username = chien@gmail.com &
password = chien

> {% client.global.set("refresh_token", response.body.refresh_token); %}

### get new access token
POST http://{{host}}:8081/api/auth/token
Content-Type: application/x-www-form-urlencoded

client_id = zing-mp3-api &
client_secret = nGZ3VfUaC8CrnmSEs8wK1J15M4PY1lUD &
grant_type = refresh_token &
refresh_token = {{refresh_token}}