/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package hcmus.zingmp3.artist.model;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ArtistEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4034206749874197178L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ArtistEvent\",\"namespace\":\"hcmus.zingmp3.artist.model\",\"fields\":[{\"name\":\"eventType\",\"type\":\"string\"},{\"name\":\"artist\",\"type\":{\"type\":\"record\",\"name\":\"ArtistAvro\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"alias\",\"type\":\"string\"},{\"name\":\"playlistId\",\"type\":\"string\"},{\"name\":\"thumbnail\",\"type\":\"string\"},{\"name\":\"totalFollow\",\"type\":\"int\"},{\"name\":\"sortBiography\",\"type\":\"string\"},{\"name\":\"biography\",\"type\":\"string\"},{\"name\":\"national\",\"type\":\"string\"},{\"name\":\"realName\",\"type\":\"string\"},{\"name\":\"birthday\",\"type\":\"string\"},{\"name\":\"awards\",\"type\":{\"type\":\"array\",\"items\":\"string\"}},{\"name\":\"songs\",\"type\":{\"type\":\"array\",\"items\":\"string\"}}]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ArtistEvent> ENCODER =
      new BinaryMessageEncoder<ArtistEvent>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ArtistEvent> DECODER =
      new BinaryMessageDecoder<ArtistEvent>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<ArtistEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<ArtistEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ArtistEvent>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this ArtistEvent to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a ArtistEvent from a ByteBuffer. */
  public static ArtistEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public CharSequence eventType;
  @Deprecated public ArtistAvro artist;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ArtistEvent() {}

  /**
   * All-args constructor.
   * @param eventType The new value for eventType
   * @param artist The new value for artist
   */
  public ArtistEvent(CharSequence eventType, ArtistAvro artist) {
    this.eventType = eventType;
    this.artist = artist;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public Object get(int field$) {
    switch (field$) {
    case 0: return eventType;
    case 1: return artist;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: eventType = (CharSequence)value$; break;
    case 1: artist = (ArtistAvro)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'eventType' field.
   * @return The value of the 'eventType' field.
   */
  public CharSequence getEventType() {
    return eventType;
  }

  /**
   * Sets the value of the 'eventType' field.
   * @param value the value to set.
   */
  public void setEventType(CharSequence value) {
    this.eventType = value;
  }

  /**
   * Gets the value of the 'artist' field.
   * @return The value of the 'artist' field.
   */
  public ArtistAvro getArtist() {
    return artist;
  }

  /**
   * Sets the value of the 'artist' field.
   * @param value the value to set.
   */
  public void setArtist(ArtistAvro value) {
    this.artist = value;
  }

  /**
   * Creates a new ArtistEvent RecordBuilder.
   * @return A new ArtistEvent RecordBuilder
   */
  public static Builder newBuilder() {
    return new Builder();
  }

  /**
   * Creates a new ArtistEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ArtistEvent RecordBuilder
   */
  public static Builder newBuilder(Builder other) {
    return new Builder(other);
  }

  /**
   * Creates a new ArtistEvent RecordBuilder by copying an existing ArtistEvent instance.
   * @param other The existing instance to copy.
   * @return A new ArtistEvent RecordBuilder
   */
  public static Builder newBuilder(ArtistEvent other) {
    return new Builder(other);
  }

  /**
   * RecordBuilder for ArtistEvent instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ArtistEvent>
    implements org.apache.avro.data.RecordBuilder<ArtistEvent> {

    private CharSequence eventType;
    private ArtistAvro artist;
    private ArtistAvro.Builder artistBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.eventType)) {
        this.eventType = data().deepCopy(fields()[0].schema(), other.eventType);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.artist)) {
        this.artist = data().deepCopy(fields()[1].schema(), other.artist);
        fieldSetFlags()[1] = true;
      }
      if (other.hasArtistBuilder()) {
        this.artistBuilder = ArtistAvro.newBuilder(other.getArtistBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing ArtistEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(ArtistEvent other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.eventType)) {
        this.eventType = data().deepCopy(fields()[0].schema(), other.eventType);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.artist)) {
        this.artist = data().deepCopy(fields()[1].schema(), other.artist);
        fieldSetFlags()[1] = true;
      }
      this.artistBuilder = null;
    }

    /**
      * Gets the value of the 'eventType' field.
      * @return The value.
      */
    public CharSequence getEventType() {
      return eventType;
    }

    /**
      * Sets the value of the 'eventType' field.
      * @param value The value of 'eventType'.
      * @return This builder.
      */
    public Builder setEventType(CharSequence value) {
      validate(fields()[0], value);
      this.eventType = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'eventType' field has been set.
      * @return True if the 'eventType' field has been set, false otherwise.
      */
    public boolean hasEventType() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'eventType' field.
      * @return This builder.
      */
    public Builder clearEventType() {
      eventType = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'artist' field.
      * @return The value.
      */
    public ArtistAvro getArtist() {
      return artist;
    }

    /**
      * Sets the value of the 'artist' field.
      * @param value The value of 'artist'.
      * @return This builder.
      */
    public Builder setArtist(ArtistAvro value) {
      validate(fields()[1], value);
      this.artistBuilder = null;
      this.artist = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'artist' field has been set.
      * @return True if the 'artist' field has been set, false otherwise.
      */
    public boolean hasArtist() {
      return fieldSetFlags()[1];
    }

    /**
     * Gets the Builder instance for the 'artist' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public ArtistAvro.Builder getArtistBuilder() {
      if (artistBuilder == null) {
        if (hasArtist()) {
          setArtistBuilder(ArtistAvro.newBuilder(artist));
        } else {
          setArtistBuilder(ArtistAvro.newBuilder());
        }
      }
      return artistBuilder;
    }

    /**
     * Sets the Builder instance for the 'artist' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public Builder setArtistBuilder(ArtistAvro.Builder value) {
      clearArtist();
      artistBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'artist' field has an active Builder instance
     * @return True if the 'artist' field has an active Builder instance
     */
    public boolean hasArtistBuilder() {
      return artistBuilder != null;
    }

    /**
      * Clears the value of the 'artist' field.
      * @return This builder.
      */
    public Builder clearArtist() {
      artist = null;
      artistBuilder = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ArtistEvent build() {
      try {
        ArtistEvent record = new ArtistEvent();
        record.eventType = fieldSetFlags()[0] ? this.eventType : (CharSequence) defaultValue(fields()[0]);
        if (artistBuilder != null) {
          record.artist = this.artistBuilder.build();
        } else {
          record.artist = fieldSetFlags()[1] ? this.artist : (ArtistAvro) defaultValue(fields()[1]);
        }
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ArtistEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<ArtistEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ArtistEvent>
    READER$ = (org.apache.avro.io.DatumReader<ArtistEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
