spring:
  application:
    name: song-service
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: mysql
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/song_service?createDatabaseIfNotExit=true
    username: zingmp3
    password: zingmp3
    driver-class-name: com.mysql.cj.jdbc.Driver
  graphql:
    graphiql:
      enabled: true

grpc:
  server:
    port: 9090
server:
  port: 0
#  http2:
#    enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    non-secure-port: ${grpc.server.port}
