spring:
  datasource:
    url: jdbc:mysql://mysql-song:3306/song_service
grpc:
  server:
    port: 0
server:
  port: 0
eureka:
  client:
    service-url:
      default-zone: http://discovery-service:8761/eureka
