spring:
  application:
    name: song-service
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/song_service
    username: zingmp3
    password: zingmp3
    driver-class-name: com.mysql.cj.jdbc.Driver
  graphql:
    graphiql:
      enabled: true
#server:
#  http2:
#    enabled: true
grpc:
  server:
    port: 9090
server:
  port: 8080
