/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package hcmus.zingmp3.award.model;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class AwardEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8898639673660338226L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AwardEvent\",\"namespace\":\"hcmus.zingmp3.award.model\",\"fields\":[{\"name\":\"eventType\",\"type\":\"string\",\"default\":\"\"},{\"name\":\"award\",\"type\":{\"type\":\"record\",\"name\":\"AwardAvro\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"name\",\"type\":\"string\"}]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AwardEvent> ENCODER =
      new BinaryMessageEncoder<AwardEvent>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AwardEvent> DECODER =
      new BinaryMessageDecoder<AwardEvent>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<AwardEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<AwardEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<AwardEvent>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this AwardEvent to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a AwardEvent from a ByteBuffer. */
  public static AwardEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence eventType;
  @Deprecated public hcmus.zingmp3.award.model.AwardAvro award;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AwardEvent() {}

  /**
   * All-args constructor.
   * @param eventType The new value for eventType
   * @param award The new value for award
   */
  public AwardEvent(java.lang.CharSequence eventType, hcmus.zingmp3.award.model.AwardAvro award) {
    this.eventType = eventType;
    this.award = award;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return eventType;
    case 1: return award;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: eventType = (java.lang.CharSequence)value$; break;
    case 1: award = (hcmus.zingmp3.award.model.AwardAvro)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'eventType' field.
   * @return The value of the 'eventType' field.
   */
  public java.lang.CharSequence getEventType() {
    return eventType;
  }

  /**
   * Sets the value of the 'eventType' field.
   * @param value the value to set.
   */
  public void setEventType(java.lang.CharSequence value) {
    this.eventType = value;
  }

  /**
   * Gets the value of the 'award' field.
   * @return The value of the 'award' field.
   */
  public hcmus.zingmp3.award.model.AwardAvro getAward() {
    return award;
  }

  /**
   * Sets the value of the 'award' field.
   * @param value the value to set.
   */
  public void setAward(hcmus.zingmp3.award.model.AwardAvro value) {
    this.award = value;
  }

  /**
   * Creates a new AwardEvent RecordBuilder.
   * @return A new AwardEvent RecordBuilder
   */
  public static hcmus.zingmp3.award.model.AwardEvent.Builder newBuilder() {
    return new hcmus.zingmp3.award.model.AwardEvent.Builder();
  }

  /**
   * Creates a new AwardEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AwardEvent RecordBuilder
   */
  public static hcmus.zingmp3.award.model.AwardEvent.Builder newBuilder(hcmus.zingmp3.award.model.AwardEvent.Builder other) {
    return new hcmus.zingmp3.award.model.AwardEvent.Builder(other);
  }

  /**
   * Creates a new AwardEvent RecordBuilder by copying an existing AwardEvent instance.
   * @param other The existing instance to copy.
   * @return A new AwardEvent RecordBuilder
   */
  public static hcmus.zingmp3.award.model.AwardEvent.Builder newBuilder(hcmus.zingmp3.award.model.AwardEvent other) {
    return new hcmus.zingmp3.award.model.AwardEvent.Builder(other);
  }

  /**
   * RecordBuilder for AwardEvent instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AwardEvent>
    implements org.apache.avro.data.RecordBuilder<AwardEvent> {

    private java.lang.CharSequence eventType;
    private hcmus.zingmp3.award.model.AwardAvro award;
    private hcmus.zingmp3.award.model.AwardAvro.Builder awardBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(hcmus.zingmp3.award.model.AwardEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.eventType)) {
        this.eventType = data().deepCopy(fields()[0].schema(), other.eventType);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.award)) {
        this.award = data().deepCopy(fields()[1].schema(), other.award);
        fieldSetFlags()[1] = true;
      }
      if (other.hasAwardBuilder()) {
        this.awardBuilder = hcmus.zingmp3.award.model.AwardAvro.newBuilder(other.getAwardBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing AwardEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(hcmus.zingmp3.award.model.AwardEvent other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.eventType)) {
        this.eventType = data().deepCopy(fields()[0].schema(), other.eventType);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.award)) {
        this.award = data().deepCopy(fields()[1].schema(), other.award);
        fieldSetFlags()[1] = true;
      }
      this.awardBuilder = null;
    }

    /**
      * Gets the value of the 'eventType' field.
      * @return The value.
      */
    public java.lang.CharSequence getEventType() {
      return eventType;
    }

    /**
      * Sets the value of the 'eventType' field.
      * @param value The value of 'eventType'.
      * @return This builder.
      */
    public hcmus.zingmp3.award.model.AwardEvent.Builder setEventType(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.eventType = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'eventType' field has been set.
      * @return True if the 'eventType' field has been set, false otherwise.
      */
    public boolean hasEventType() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'eventType' field.
      * @return This builder.
      */
    public hcmus.zingmp3.award.model.AwardEvent.Builder clearEventType() {
      eventType = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'award' field.
      * @return The value.
      */
    public hcmus.zingmp3.award.model.AwardAvro getAward() {
      return award;
    }

    /**
      * Sets the value of the 'award' field.
      * @param value The value of 'award'.
      * @return This builder.
      */
    public hcmus.zingmp3.award.model.AwardEvent.Builder setAward(hcmus.zingmp3.award.model.AwardAvro value) {
      validate(fields()[1], value);
      this.awardBuilder = null;
      this.award = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'award' field has been set.
      * @return True if the 'award' field has been set, false otherwise.
      */
    public boolean hasAward() {
      return fieldSetFlags()[1];
    }

    /**
     * Gets the Builder instance for the 'award' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public hcmus.zingmp3.award.model.AwardAvro.Builder getAwardBuilder() {
      if (awardBuilder == null) {
        if (hasAward()) {
          setAwardBuilder(hcmus.zingmp3.award.model.AwardAvro.newBuilder(award));
        } else {
          setAwardBuilder(hcmus.zingmp3.award.model.AwardAvro.newBuilder());
        }
      }
      return awardBuilder;
    }

    /**
     * Sets the Builder instance for the 'award' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public hcmus.zingmp3.award.model.AwardEvent.Builder setAwardBuilder(hcmus.zingmp3.award.model.AwardAvro.Builder value) {
      clearAward();
      awardBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'award' field has an active Builder instance
     * @return True if the 'award' field has an active Builder instance
     */
    public boolean hasAwardBuilder() {
      return awardBuilder != null;
    }

    /**
      * Clears the value of the 'award' field.
      * @return This builder.
      */
    public hcmus.zingmp3.award.model.AwardEvent.Builder clearAward() {
      award = null;
      awardBuilder = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AwardEvent build() {
      try {
        AwardEvent record = new AwardEvent();
        record.eventType = fieldSetFlags()[0] ? this.eventType : (java.lang.CharSequence) defaultValue(fields()[0]);
        if (awardBuilder != null) {
          record.award = this.awardBuilder.build();
        } else {
          record.award = fieldSetFlags()[1] ? this.award : (hcmus.zingmp3.award.model.AwardAvro) defaultValue(fields()[1]);
        }
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AwardEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<AwardEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AwardEvent>
    READER$ = (org.apache.avro.io.DatumReader<AwardEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
