@host = localhost

### POST create an award
POST http://{{host}}:8082/api/award
Content-Type: application/json

{
    "name": "Nghệ sĩ xuất sắc nhất tháng 2."
}

> {%
    client.global.set("awardId1", response.body.id);
%}

### POST create an award
POST http://{{host}}:8082/api/award
Content-Type: application/json

{
  "name": "Nghệ sĩ xuất sắc nhất năm"
}

> {%
    client.global.set("awardId2", response.body.id);
%}



### POST create an artist
POST http://{{host}}:8080/api/artist
Content-Type: multipart/form-data; boundary=---011000010111000001101001

-----011000010111000001101001
Content-Disposition: form-data; name="artist"; filename="artist.json"
Content-Type: application/json

{
  "realName": "Văn Lý Hải",
  "name": "Lý Hải",
  "thumbnail": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "alias": "van-ly-hai",
  "national": "Việt Nam",
  "biography": "",
  "sortBiography": "",
  "awards": [
    "{{awardId1}}",
    "{{awardId2}}"
  ],
  "birthday": "2024-05-30"
}
-----011000010111000001101001--
